# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.webgl.trial_adders.trial_adder import TrialAdder


class AtEnd(TrialAdder):
    """
    Add trials at the end of the current list of trials.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
