# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.webgl.trial_adders.trial_adder import TrialAdder


class AtStart(TrialAdder):
    """
    Insert new trials at the start of the list of the current trials.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
