# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.robot_joint_target_command import RobotJointTargetCommand


class AddTorqueToRevolute(RobotJointTargetCommand):
    """
    Add a torque to a revolute joint.
    """

    def __init__(self, joint_id: int, torque: float, id: int = 0):
        """
        :param joint_id: The ID of the joint.
        :param torque: The torque in Newtons.
        :param id: The ID of the robot in the scene.
        """

        super().__init__(joint_id=joint_id, id=id)
        """:field
        The torque in Newtons.
        """
        self.torque: float = torque
