# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.add_object_command import AddObjectCommand
from typing import Dict


class AddVisualEffect(AddObjectCommand):
    """
    Add a non-physics visual effect to the scene from an asset bundle.
    """

    def __init__(self, url: str, name: str, id: int, position: Dict[str, float] = None, rotation: Dict[str, float] = None):
        """
        :param url: The location of the asset bundle. If the asset bundle is remote, this must be a valid URL. If the asset is a local file, this must begin with the prefix "file:///"
        :param name: The name of the asset bundle.
        :param id: The ID of this visual effect.
        :param position: The initial position of the visual effect.
        :param rotation: The initial rotation of the visual effect.
        """

        super().__init__(name=name, url=url)
        """:field
        The ID of this visual effect.
        """
        self.id: int = id
        if position is None:
            """:field
            The initial position of the visual effect.
            """
            self.position: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.position = position
        if rotation is None:
            """:field
            The initial rotation of the visual effect.
            """
            self.rotation: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.rotation = rotation
