# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.compass_rose_command import CompassRoseCommand
from typing import Dict


class AddCompassRose(CompassRoseCommand):
    """
    Add a visual compass rose to the scene. It will show which way is north, south, etc. as well as positive X, negative X, etc.
    """

    def __init__(self, position: Dict[str, float] = None):
        """
        :param position: Position of the compass rose.
        """

        super().__init__()
        if position is None:
            """:field
            Position of the compass rose.
            """
            self.position: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.position = position
