# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.add_humanoid_command import AddHumanoidCommand
from typing import Dict


class AddHumanoid(AddHumanoidCommand):
    """
    Add a humanoid model to the scene.
    """

    def __init__(self, url: str, name: str, id: int, position: Dict[str, float] = None, rotation: Dict[str, float] = None):
        """
        :param url: The location of the asset bundle. If the asset bundle is remote, this must be a valid URL. If the asset is a local file, this must begin with the prefix "file:///"
        :param name: The name of the asset bundle.
        :param id: The unique ID of the humanoid.
        :param position: Position of the humanoid.
        :param rotation: Rotation of the humanoid, in Euler angles.
        """

        super().__init__(id=id, position=position, rotation=rotation, name=name, url=url)

