# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command
from typing import Dict


class AddMagnebot(Command):
    """
    Add a Magnebot to the scene. For a high-level API, see: [https://github.com/alters-mit/magnebot](https://github.com/alters-mit/magnebot)
    """

    def __init__(self, id: int = 0, position: Dict[str, float] = None, rotation: Dict[str, float] = None):
        """
        :param id: The unique ID of the Magnebot.
        :param position: The initial position of the Magnebot.
        :param rotation: The initial rotation of the Magnebot in Euler angles.
        """

        super().__init__()
        """:field
        The unique ID of the Magnebot.
        """
        self.id: int = id
        if position is None:
            """:field
            The initial position of the Magnebot.
            """
            self.position: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.position = position
        if rotation is None:
            """:field
            The initial rotation of the Magnebot in Euler angles.
            """
            self.rotation: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.rotation = rotation
