# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.add_object_command import AddObjectCommand
from typing import Dict


class AddHumanoidCommand(AddObjectCommand, ABC):
    """
    These commands add a humanoid model to the scene.
    """

    def __init__(self, url: str, name: str, id: int, position: Dict[str, float] = None, rotation: Dict[str, float] = None):
        """
        :param url: The location of the asset bundle. If the asset bundle is remote, this must be a valid URL. If the asset is a local file, this must begin with the prefix "file:///"
        :param name: The name of the asset bundle.
        :param id: The unique ID of the humanoid.
        :param position: Position of the humanoid.
        :param rotation: Rotation of the humanoid, in Euler angles.
        """

        super().__init__(name=name, url=url)
        """:field
        The unique ID of the humanoid.
        """
        self.id: int = id
        if position is None:
            """:field
            Position of the humanoid.
            """
            self.position: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.position = position
        if rotation is None:
            """:field
            Rotation of the humanoid, in Euler angles.
            """
            self.rotation: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.rotation = rotation
