# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.add_ui_command import AddUiCommand
from typing import Dict


class AddUiText(AddUiCommand):
    """
    Add UI text to the scene.
    """

    def __init__(self, id: int, text: str, font_size: int = 14, anchor: Dict[str, float] = None, pivot: Dict[str, float] = None, position: Dict[str, int] = None, color: Dict[str, float] = None, raycast_target: bool = True, canvas_id: int = 0):
        """
        :param id: The unique ID of the UI element.
        :param text: The text.
        :param font_size: The font size.
        :param anchor: The anchor of the UI element. The values must be from 0 (left or bottom) to 1 (right or top). By default, the anchor is in the center.
        :param pivot: The pivot of the UI element. The values must be from 0 (left or bottom) to 1 (right or top). By default, the pivot is in the center.
        :param position: The anchor position of the UI element in pixels. x is lateral, y is vertical. The anchor position is not the true pixel position. For example, if the anchor is {"x": 0, "y": 0} and the position is {"x": 0, "y": 0}, the UI element will be in the bottom-left of the screen.
        :param color: The color of the UI element.
        :param raycast_target: If True, raycasts will hit the UI element.
        :param canvas_id: The unique ID of the UI canvas.
        """

        super().__init__(anchor=anchor, pivot=pivot, position=position, color=color, raycast_target=raycast_target, id=id, canvas_id=canvas_id)
        """:field
        The text.
        """
        self.text: str = text
        """:field
        The font size.
        """
        self.font_size: int = font_size
