# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.add_object_command import AddObjectCommand


class AddMaterialCommand(AddObjectCommand, ABC):
    """
    These commands add material asset bundles to the scene.
    """

    def __init__(self, url: str, name: str):
        """
        :param url: The location of the asset bundle. If the asset bundle is remote, this must be a valid URL. If the asset is a local file, this must begin with the prefix "file:///"
        :param name: The name of the asset bundle.
        """

        super().__init__(name=name, url=url)

