# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.robot_joint_target_command import RobotJointTargetCommand


class AddForceToPrismatic(RobotJointTargetCommand):
    """
    Add a force to a prismatic joint.
    """

    def __init__(self, joint_id: int, force: float, id: int = 0):
        """
        :param joint_id: The ID of the joint.
        :param force: The force in Newtons.
        :param id: The ID of the robot in the scene.
        """

        super().__init__(joint_id=joint_id, id=id)
        """:field
        The force in Newtons.
        """
        self.force: float = force
