# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.add_humanoid_command import AddHumanoidCommand
from typing import Dict


class AddSmplHumanoid(AddHumanoidCommand):
    """
    Add a parameterized humanoid to the scene using <ulink url="https://smpl.is.tue.mpg.de/en">SMPL</ulink>. Each parameter scales an aspect of the humanoid and must be between -1 and 1. For example, if the height is -1, then the humanoid will be the shortest possible height. Because all of these parameters blend together to create the overall shape, it isn't possible to document specific body shape values, such as overall height, that might correspond to this command's parameters.
    """

    def __init__(self, url: str, name: str, id: int, height: float = 0, weight: float = 0, torso_height_and_shoulder_width: float = 0, chest_breadth_and_neck_height: float = 0, upper_lower_back_ratio: float = 0, pelvis_width: float = 0, hips_curve: float = 0, torso_height: float = 0, left_right_symmetry: float = 0, shoulder_and_torso_width: float = 0, position: Dict[str, float] = None, rotation: Dict[str, float] = None):
        """
        :param url: The location of the asset bundle. If the asset bundle is remote, this must be a valid URL. If the asset is a local file, this must begin with the prefix "file:///"
        :param name: The name of the asset bundle.
        :param id: The unique ID of the humanoid.
        :param height: The height or overall scale of the model. Must be between -1 and 1.
        :param weight: The character's overall weight. Must be between -1 and 1.
        :param torso_height_and_shoulder_width: The height of the torso from the chest and the width of the shoulders. Must be between -1 and 1.
        :param chest_breadth_and_neck_height: The breadth of the chest and the height of the neck. Must be between -1 and 1.
        :param upper_lower_back_ratio: The extent to which the upper back is larger than the lower back or vice versa. Must be between -1 and 1.
        :param pelvis_width: The width of the pelvis. Must be between -1 and 1.
        :param hips_curve: The overall curviness of the hips. Must be between -1 and 1.
        :param torso_height: The height of the torso from the chest. Must be between -1 and 1.
        :param left_right_symmetry: The extent to which the left side of the mesh is slightly narrower or vice versa. Must be between -1 and 1.
        :param shoulder_and_torso_width: The width of the shoulders and torso combined. Must be between -1 and 1.
        :param position: Position of the humanoid.
        :param rotation: Rotation of the humanoid, in Euler angles.
        """

        super().__init__(id=id, position=position, rotation=rotation, name=name, url=url)
        """:field
        The height or overall scale of the model. Must be between -1 and 1.
        """
        self.height: float = height
        """:field
        The character's overall weight. Must be between -1 and 1.
        """
        self.weight: float = weight
        """:field
        The height of the torso from the chest and the width of the shoulders. Must be between -1 and 1.
        """
        self.torso_height_and_shoulder_width: float = torso_height_and_shoulder_width
        """:field
        The breadth of the chest and the height of the neck. Must be between -1 and 1.
        """
        self.chest_breadth_and_neck_height: float = chest_breadth_and_neck_height
        """:field
        The extent to which the upper back is larger than the lower back or vice versa. Must be between -1 and 1.
        """
        self.upper_lower_back_ratio: float = upper_lower_back_ratio
        """:field
        The width of the pelvis. Must be between -1 and 1.
        """
        self.pelvis_width: float = pelvis_width
        """:field
        The overall curviness of the hips. Must be between -1 and 1.
        """
        self.hips_curve: float = hips_curve
        """:field
        The height of the torso from the chest. Must be between -1 and 1.
        """
        self.torso_height: float = torso_height
        """:field
        The extent to which the left side of the mesh is slightly narrower or vice versa. Must be between -1 and 1.
        """
        self.left_right_symmetry: float = left_right_symmetry
        """:field
        The width of the shoulders and torso combined. Must be between -1 and 1.
        """
        self.shoulder_and_torso_width: float = shoulder_and_torso_width
