# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.directional_light_command import DirectionalLightCommand


class AdjustDirectionalLightIntensityBy(DirectionalLightCommand):
    """
    Adjust the intensity of the directional light (the sun) by a value.
    """

    def __init__(self, intensity: float, index: int = 0):
        """
        :param intensity: Adjust the intensity of the sunlight by this value.
        :param index: The index of the light. This should almost always be 0. The scene "archviz_house" has two directional lights; for this scene, index can be 0 or 1.
        """

        super().__init__(index=index)
        """:field
        Adjust the intensity of the sunlight by this value.
        """
        self.intensity: float = intensity
