# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command
from typing import Dict


class ApplyForce(Command):
    """
    Apply a force into the world to an target position. The force will impact any objects between the origin and the target position.
    """

    def __init__(self, magnitude: float, target: Dict[str, float], origin: Dict[str, float]):
        """
        :param magnitude: The magnitude of the force.
        :param target: The target position of the force.
        :param origin: The origin of the force.
        """

        super().__init__()
        """:field
        The origin of the force.
        """
        self.origin: Dict[str, float] = origin
        """:field
        The target position of the force.
        """
        self.target: Dict[str, float] = target
        """:field
        The magnitude of the force.
        """
        self.magnitude: float = magnitude
