# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.flex_object_command import FlexObjectCommand
from typing import Dict


class ApplyForceToFlexObject(FlexObjectCommand):
    """
    Apply a directional force to the FlexActor object.
    """

    def __init__(self, id: int, force: Dict[str, float], particle: int = -1):
        """
        :param id: The unique object ID.
        :param force: The directional force.
        :param particle: The particle index. Must be smaller than the total number of particles in the Flex actor. If -1, force is applied to all object particles.
        """

        super().__init__(id=id)
        """:field
        The directional force.
        """
        self.force: Dict[str, float] = force
        """:field
        The particle index. Must be smaller than the total number of particles in the Flex actor. If -1, force is applied to all object particles.
        """
        self.particle: int = particle
