# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_type_command import ObjectTypeCommand
from typing import Dict


class ApplyTorqueToObject(ObjectTypeCommand):
    """
    Apply a torque to the object's rigidbody.
    """

    def __init__(self, id: int, torque: Dict[str, float] = None):
        """
        :param id: The unique object ID.
        :param torque: The torque force.
        """

        super().__init__(id=id)
        if torque is None:
            """:field
            The torque force.
            """
            self.torque: Dict[str, float] = {"x": 1, "y": 1, "z": 1}
        else:
            self.torque = torque
