# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.drone_command import DroneCommand


class ApplyDroneLift(DroneCommand):
    """
    Control the drone's elevation above the ground. Positive numbers cause the drone to rise, negative numbers cause it to descend. A zero value will cause it to maintain its current elevation.
    """

    def __init__(self, id: int, force: int = 0):
        """
        :param id: The unique object ID.
        :param force: The force value. Must be -1, 0, or 1.
        """

        super().__init__(id=id)
        """:field
        The force value. Must be -1, 0, or 1.
        """
        self.force: int = force
