# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_type_command import ObjectTypeCommand
from tdw.obi_data.force_mode import ForceMode
from typing import Dict


class ApplyTorqueToObiCloth(ObjectTypeCommand):
    """
    Apply a uniform torque to an Obi cloth actor.
    """

    def __init__(self, id: int, torque: Dict[str, float] = None, force_mode: ForceMode = ForceMode.impulse):
        """
        :param id: The unique object ID.
        :param torque: The torque.
        :param force_mode: The force mode.
        """

        super().__init__(id=id)
        if torque is None:
            """:field
            The torque.
            """
            self.torque: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.torque = torque
        """:field
        The force mode.
        """
        self.force_mode: ForceMode = force_mode
