# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.flex_object_command import FlexObjectCommand


class ApplyForcesToFlexObjectBase64(FlexObjectCommand):
    """
    Apply a directional force to the FlexActor object.
    """

    def __init__(self, id: int, forces_and_ids_base64: str):
        """
        :param id: The unique object ID.
        :param forces_and_ids_base64: A list of directional forces [x,y,z] and ids of particles to which each force is applied. Format is [[f1_x, f1_y, f1_z, f1_id], [f2_x, f2_y, f2_z, f2_id], ...].
        """

        super().__init__(id=id)
        """:field
        A list of directional forces [x,y,z] and ids of particles to which each force is applied. Format is [[f1_x, f1_y, f1_z, f1_id], [f2_x, f2_y, f2_z, f2_id], ...].
        """
        self.forces_and_ids_base64: str = forces_and_ids_base64
