# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.avatar_rigidbody_command import AvatarRigidbodyCommand
from typing import Dict


class ApplyForceToAvatar(AvatarRigidbodyCommand):
    """
    Apply a force to the avatar.
    """

    def __init__(self, magnitude: float, direction: Dict[str, float] = None, avatar_id: str = "a"):
        """
        :param magnitude: The magnitude of the force.
        :param direction: The direction of the force.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(avatar_id=avatar_id)
        if direction is None:
            """:field
            The direction of the force.
            """
            self.direction: Dict[str, float] = {"x": 0, "y": 0, "z": 1}
        else:
            self.direction = direction
        """:field
        The magnitude of the force.
        """
        self.magnitude: float = magnitude
