# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.flex_object_command import FlexObjectCommand


class AssignFlexContainer(FlexObjectCommand):
    """
    Assign the FlexContainer of the object.
    """

    def __init__(self, id: int, container_id: int, fluid_container: bool = False, fluid_type: str = "water"):
        """
        :param id: The unique object ID.
        :param container_id: The unique ID of the container.
        :param fluid_container: Is this a fluid container?
        :param fluid_type: Type of fluid to use for this container.
        """

        super().__init__(id=id)
        """:field
        The unique ID of the container.
        """
        self.container_id: int = container_id
        """:field
        Is this a fluid container?
        """
        self.fluid_container: bool = fluid_container
        """:field
        Type of fluid to use for this container.
        """
        self.fluid_type: str = fluid_type
