# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.vr_command import VrCommand


class AttachAvatarToVrRig(VrCommand):
    """
    Attach an avatar (A_Img_Caps_Kinematic) to the VR rig in the scene. This avatar will work like all others, i.e it can send images and other data. The avatar will match the position and rotation of the VR rig's head. By default, this feature is disabled because it slows down the simulation's FPS.
    """

    def __init__(self, id: str):
        """
        :param id: ID of this avatar. Must be unique.
        """

        super().__init__()
        """:field
        ID of this avatar. Must be unique.
        """
        self.id: str = id
