# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.ui_command import UiCommand


class AttachUiCanvasToAvatar(UiCommand):
    """
    Attach a UI canvas to an avatar. This allows the UI to appear in image output data.
    """

    def __init__(self, avatar_id: str = "a", plane_distance: float = 0.101, canvas_id: int = 0):
        """
        :param avatar_id: The ID of the avatar.
        :param plane_distance: The distance from the camera to the UI canvas. This should be slightly further than the near clipping plane.
        :param canvas_id: The unique ID of the UI canvas.
        """

        super().__init__(canvas_id=canvas_id)
        """:field
        The ID of the avatar.
        """
        self.avatar_id: str = avatar_id
        """:field
        The distance from the camera to the UI canvas. This should be slightly further than the near clipping plane.
        """
        self.plane_distance: float = plane_distance
