# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.simple_body_command import SimpleBodyCommand


class ChangeAvatarBody(SimpleBodyCommand):
    """
    Change the body of a SimpleBodyAvatar.
    """

    def __init__(self, body_type: str, avatar_id: str = "a"):
        """
        :param body_type: The body type of the avatar.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(avatar_id=avatar_id)
        """:field
        The body type of the avatar.
        """
        self.body_type: str = body_type
