# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC


class Command(ABC):
    """
    Abstract class for a message sent from the controller to the build.
    """

    def __init__(self):
        """
        (no arguments)
        """

        pass
