# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.proc_gen_room_command import ProcGenRoomCommand


class CreateProcGenCeiling(ProcGenRoomCommand):
    """
    Create a ceiling for the procedurally generated room. The ceiling is divided into 1x1 "tiles", which can be manipulated with Proc Gen Ceiling Tiles Commands (see below).
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
