# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.textured_quad_command import TexturedQuadCommand
from typing import Dict


class CreateTexturedQuad(TexturedQuadCommand):
    """
    Create a blank quad (a rectangular mesh with four vertices) in the scene.
    """

    def __init__(self, id: int, euler_angles: Dict[str, float], size: Dict[str, float], position: Dict[str, float]):
        """
        :param id: The ID of the non-physics object.
        :param euler_angles: The orientation of the quad, in Euler angles.
        :param size: The width and height of the quad.
        :param position: The position of the quad. This will always be anchored in the bottom-center point of the object.
        """

        super().__init__(id=id)
        """:field
        The position of the quad. This will always be anchored in the bottom-center point of the object.
        """
        self.position: Dict[str, float] = position
        """:field
        The width and height of the quad.
        """
        self.size: Dict[str, float] = size
        """:field
        The orientation of the quad, in Euler angles.
        """
        self.euler_angles: Dict[str, float] = euler_angles
