# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.floor_command import FloorCommand


class CreateFloorObiColliders(FloorCommand):
    """
    Create Obi colliders for the floor if there aren't any.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
