# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.robot_command import RobotCommand


class CreateRobotObiColliders(RobotCommand):
    """
    Create Obi colliders for a robot if there aren't any.
    """

    def __init__(self, id: int = 0):
        """
        :param id: The ID of the robot in the scene.
        """

        super().__init__(id=id)

