# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command
from typing import Dict


class CreateEmptyEnvironment(Command):
    """
    Create an empty environment. This must be called after load_scene.
    """

    def __init__(self, center: Dict[str, float] = None, bounds: Dict[str, float] = None):
        """
        :param center: Centerpoint of this environment.
        :param bounds: Spatial bounds (width, height, length) of the environment.
        """

        super().__init__()
        if center is None:
            """:field
            Centerpoint of this environment.
            """
            self.center: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.center = center
        if bounds is None:
            """:field
            Spatial bounds (width, height, length) of the environment.
            """
            self.bounds: Dict[str, float] = {}
        else:
            self.bounds = bounds
