# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.create_obi_actor_command import CreateObiActorCommand
from tdw.obi_data.fluids.emitter_shape import EmitterShape
from tdw.obi_data.fluids.fluid_base import FluidBase
from typing import Dict


class CreateObiFluid(CreateObiActorCommand):
    """
    Create an Obi fluid. Obi fluids have three components: The emitter, the fluid, and the shape of the emitter.
    """

    def __init__(self, shape: EmitterShape, fluid: FluidBase, lifespan: float = 4, minimum_pool_size: float = 0.5, speed: float = 0, position: Dict[str, float] = None, rotation: Dict[str, float] = None, id: int = 0, solver_id: int = 0):
        """
        :param shape: A ../python/obi_data/emitter_shape/cube_emitter.md "`CubeEmitter`", ../python/obi_data/emitter_shape/disk_emitter.md "`DiskEmitter`", ../python/obi_data/emitter_shape/edge_emitter.md "`EdgeEmitter`", or ../python/obi_data/emitter_shape/sphere_emitter.md "`SphereEmitter`".
        :param fluid: A ../python/obi_data/fluid.md "`Fluid`" or ../python/obi_data/granular_fluid.md "`GranularFluid`"
        :param lifespan: The particle lifespan in seconds.
        :param minimum_pool_size: The minimum amount of inactive particles available before the emitter is allowed to resume emission.
        :param speed: The speed of the fluid emission. If 0, there is no emission.
        :param position: The position of the Obi actor.
        :param rotation: The rotation of the Obi actor in Euler angles.
        :param id: The unique ID of the emitter.
        :param solver_id: The ID of the Obi solver.
        """

        super().__init__(position=position, rotation=rotation, id=id, solver_id=solver_id)
        """:field
        A ../python/obi_data/fluid.md "`Fluid`" or ../python/obi_data/granular_fluid.md "`GranularFluid`"
        """
        self.fluid: FluidBase = fluid
        """:field
        A ../python/obi_data/emitter_shape/cube_emitter.md "`CubeEmitter`", ../python/obi_data/emitter_shape/disk_emitter.md "`DiskEmitter`", ../python/obi_data/emitter_shape/edge_emitter.md "`EdgeEmitter`", or ../python/obi_data/emitter_shape/sphere_emitter.md "`SphereEmitter`".
        """
        self.shape: EmitterShape = shape
        """:field
        The particle lifespan in seconds.
        """
        self.lifespan: float = lifespan
        """:field
        The minimum amount of inactive particles available before the emitter is allowed to resume emission.
        """
        self.minimum_pool_size: float = minimum_pool_size
        """:field
        The speed of the fluid emission. If 0, there is no emission.
        """
        self.speed: float = speed
