# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.compass_rose_command import CompassRoseCommand


class DestroyCompassRose(CompassRoseCommand):
    """
    Destroy the compasss rose in the scene.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
