# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.obi_command import ObiCommand


class DestroyObiSolver(ObiCommand):
    """
    Destroy an Obi solver.
    """

    def __init__(self, solver_id: int = 0):
        """
        :param solver_id: The solver ID.
        """

        super().__init__()
        """:field
        The solver ID.
        """
        self.solver_id: int = solver_id
