# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.vr_command import VrCommand


class DestroyVrRig(VrCommand):
    """
    Destroy the current VR rig.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
