# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.flex_container_command import FlexContainerCommand


class DestroyFlexContainer(FlexContainerCommand):
    """
    Destroy an existing Flex container. Only send this command after destroying all Flex objects in the scene.
    """

    def __init__(self, id: int = 0):
        """
        :param id: The ID of the existing container.
        """

        super().__init__()
        """:field
        The ID of the existing container.
        """
        self.id: int = id
