# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.proc_gen_ceiling_tiles_command import ProcGenCeilingTilesCommand
from typing import Dict, List


class DestroyProcGenCeilingTiles(ProcGenCeilingTilesCommand):
    """
    Destroy ceiling tiles from a procedurally-created ceiling.
    """

    def __init__(self, ceiling_tiles: List[Dict[str, float]]):
        """
        :param ceiling_tiles: The list of ceiling tile positions.
        """

        super().__init__(ceiling_tiles=ceiling_tiles)

