# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.object_type_command import ObjectTypeCommand


class DroneCommand(ObjectTypeCommand, ABC):
    """
    These commands affect a drone currently in the scene.
    """

    def __init__(self, id: int):
        """
        :param id: The unique object ID.
        """

        super().__init__(id=id)

