# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.object_command import ObjectCommand


class EmptyObjectCommand(ObjectCommand, ABC):
    """
    These commands add or adjust an empty object attached to an object.
    """

    def __init__(self, id: int, empty_object_id: int):
        """
        :param id: The unique object ID.
        :param empty_object_id: The ID of the empty object. This doesn't have to be the same as the object ID.
        """

        super().__init__(id=id)
        """:field
        The ID of the empty object. This doesn't have to be the same as the object ID.
        """
        self.empty_object_id: int = empty_object_id
