# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command


class EnableReflectionProbes(Command):
    """
    Enable or disable the reflection probes in the scene. By default, the reflection probes are enabled. Disabling the reflection probes will yield less realistic images but will improve the speed of the simulation.
    """

    def __init__(self, enable: bool = True):
        """
        :param enable: If True, the reflection probes will be enabled.
        """

        super().__init__()
        """:field
        If True, the reflection probes will be enabled.
        """
        self.enable: bool = enable
