# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.focus_on_object_command import FocusOnObjectCommand


class FocusOnObject(FocusOnObjectCommand):
    """
    Set the post-process depth of field focus distance to equal the distance between the avatar and an object. This won't adjust the angle or position of the avatar's camera.
    """

    def __init__(self, object_id: int, use_centroid: bool = False, sensor_name: str = "SensorContainer", avatar_id: str = "a"):
        """
        :param object_id: The ID of the object.
        :param use_centroid: If true, look at the centroid of the object. This is computationally expensive. If false, look at the position of the object (y=0).
        :param sensor_name: The name of the target sensor.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(object_id=object_id, use_centroid=use_centroid, sensor_name=sensor_name, avatar_id=avatar_id)

