# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.sensor_container_command import SensorContainerCommand


class LookAt(SensorContainerCommand):
    """
    Look at an object (rotate the image sensor to center the object in the frame).
    """

    def __init__(self, use_centroid: bool, object_id: int, sensor_name: str = "SensorContainer", avatar_id: str = "a"):
        """
        :param use_centroid: If true, look at the centroid of the object. If false, look at the position of the object (y=0).
        :param object_id: The ID of the object we want the avatar to look at.
        :param sensor_name: The name of the target sensor.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(sensor_name=sensor_name, avatar_id=avatar_id)
        """:field
        The ID of the object we want the avatar to look at.
        """
        self.object_id: int = object_id
        """:field
        If true, look at the centroid of the object. If false, look at the position of the object (y=0).
        """
        self.use_centroid: bool = use_centroid
