# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.sensor_container_command import SensorContainerCommand
from typing import Dict


class LookAtPosition(SensorContainerCommand):
    """
    Look at a worldspace position (rotate the image sensor to center the position in the frame).
    """

    def __init__(self, position: Dict[str, float], sensor_name: str = "SensorContainer", avatar_id: str = "a"):
        """
        :param position: The worldspace position that the avatar should look at.
        :param sensor_name: The name of the target sensor.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(sensor_name=sensor_name, avatar_id=avatar_id)
        """:field
        The worldspace position that the avatar should look at.
        """
        self.position: Dict[str, float] = position
