# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.move_avatar_towards import MoveAvatarTowards
from typing import Dict


class MoveAvatarTowardsObject(MoveAvatarTowards):
    """
    Move the avatar towards an object.
    """

    def __init__(self, offset: Dict[str, float], object_id: int, use_centroid: bool = True, speed: float = 0.1, avatar_id: str = "a"):
        """
        :param offset: The offset the position of the avatar from the object.
        :param object_id: The ID of the object.
        :param use_centroid: If true, move towards the centroid of the object. If false, move towards the position of the object (y=0).
        :param speed: Move a maximum of this many meters per frame towards the target.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(speed=speed, avatar_id=avatar_id)
        """:field
        The ID of the object.
        """
        self.object_id: int = object_id
        """:field
        The offset the position of the avatar from the object.
        """
        self.offset: Dict[str, float] = offset
        """:field
        If true, move towards the centroid of the object. If false, move towards the position of the object (y=0).
        """
        self.use_centroid: bool = use_centroid
