# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.avatar_rigidbody_command import AvatarRigidbodyCommand
from typing import Dict


class MoveAvatarTo(AvatarRigidbodyCommand):
    """
    Move the position of the avatar's rigidbody. This is very similar to teleport_avatar_to, but it is a physics-based motion, and will comply with physics interpolation.
    """

    def __init__(self, position: Dict[str, float], avatar_id: str = "a"):
        """
        :param position: The new position of the avatar.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(avatar_id=avatar_id)
        """:field
        The new position of the avatar.
        """
        self.position: Dict[str, float] = position
