# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.object_command import ObjectCommand


class ObjectTypeCommand(ObjectCommand, ABC):
    """
    These commands affect only objects of a specific type.
    """

    def __init__(self, id: int):
        """
        :param id: The unique object ID.
        """

        super().__init__(id=id)

