# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.drone_command import DroneCommand


class ParentAvatarToDrone(DroneCommand):
    """
    Parent an avatar to a drone. Usually you'll want to do this to add a camera to the drone.
    """

    def __init__(self, id: int, avatar_id: str = "a"):
        """
        :param id: The unique object ID.
        :param avatar_id: The ID of the avatar. It must already exist in the scene.
        """

        super().__init__(id=id)
        """:field
        The ID of the avatar. It must already exist in the scene.
        """
        self.avatar_id: str = avatar_id
