# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_command import ObjectCommand


class ParentObjectToObject(ObjectCommand):
    """
    Parent an object to an object. In a non-physics simulation or on the frame that the two objects are first created, rotating or moving the parent object will rotate or move the child object. In subsequent physics steps, the child will move independently of the parent object (like any object).
    """

    def __init__(self, id: int, parent_id: int):
        """
        :param id: The unique object ID.
        :param parent_id: The ID of the parent object in the scene.
        """

        super().__init__(id=id)
        """:field
        The ID of the parent object in the scene.
        """
        self.parent_id: int = parent_id
