# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.adjust_visual_effect_command import AdjustVisualEffectCommand


class ParentVisualEffectToObject(AdjustVisualEffectCommand):
    """
    Parent a non-physical visual effect to a standard TDW physically-embodied object.
    """

    def __init__(self, id: int, object_id: int):
        """
        :param id: The ID of the non-physics object.
        :param object_id: The ID of the physically-embodied TDW object.
        """

        super().__init__(id=id)
        """:field
        The ID of the physically-embodied TDW object.
        """
        self.object_id: int = object_id
