# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.adjust_textured_quad_command import AdjustTexturedQuadCommand


class ParentTexturedQuadToObject(AdjustTexturedQuadCommand):
    """
    Parent a textured quad to an object in the scene. The textured quad will always be at a fixed local position and rotation relative to the object.
    """

    def __init__(self, id: int, object_id: int):
        """
        :param id: The ID of the non-physics object.
        :param object_id: The ID of the parent object in the scene.
        """

        super().__init__(id=id)
        """:field
        The ID of the parent object in the scene.
        """
        self.object_id: int = object_id
