# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.play_audio_command import PlayAudioCommand
from typing import Dict


class PlayAudioDataCommand(PlayAudioCommand, ABC):
    """
    Play audio at a position.
    """

    def __init__(self, id: int, num_frames: int, wav_data: str, frame_rate: int = 44100, num_channels: int = 1, position: Dict[str, float] = None, loop: bool = False):
        """
        :param id: A unique ID for this audio source.
        :param num_frames: The number of audio frames in the audio data.
        :param wav_data: Base64 string representation of an audio data byte array.
        :param frame_rate: The sample rate of the audio data (default = 44100).
        :param num_channels: The number of audio channels (1 or 2; default = 1).
        :param position: The position of the audio source.
        :param loop: If True, play the audio in a continuous loop.
        """

        super().__init__(id=id, position=position, loop=loop)
        """:field
        Base64 string representation of an audio data byte array.
        """
        self.wav_data: str = wav_data
        """:field
        The number of audio frames in the audio data.
        """
        self.num_frames: int = num_frames
        """:field
        The sample rate of the audio data (default = 44100).
        """
        self.frame_rate: int = frame_rate
        """:field
        The number of audio channels (1 or 2; default = 1).
        """
        self.num_channels: int = num_channels
