# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.command import Command


class PostProcessCommand(Command, ABC):
    """
    These commands adjust post-processing values.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
