# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.proc_gen_room_command import ProcGenRoomCommand
from typing import Dict, List


class ProcGenCeilingTilesCommand(ProcGenRoomCommand, ABC):
    """
    These commands affect specific ceiling tiles. To use these commands, you must create a ceiling first by sending create_proc_gen_ceiling.
    """

    def __init__(self, ceiling_tiles: List[Dict[str, float]]):
        """
        :param ceiling_tiles: The list of ceiling tile positions.
        """

        super().__init__()
        """:field
        The list of ceiling tile positions.
        """
        self.ceiling_tiles: List[Dict[str, float]] = ceiling_tiles
