# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.robot_command import RobotCommand


class RemoveRobotNavMeshObstacle(RobotCommand):
    """
    Remove a NavMesh obstacle from a robot (see make_robot_nav_mesh_obstacle).
    """

    def __init__(self, id: int = 0):
        """
        :param id: The ID of the robot in the scene.
        """

        super().__init__(id=id)

