# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_command import ObjectCommand


class RemoveNavMeshObstacle(ObjectCommand):
    """
    Remove a NavMesh obstacle from an object (see make_nav_mesh_obstacle).
    """

    def __init__(self, id: int):
        """
        :param id: The unique object ID.
        """

        super().__init__(id=id)

