# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.replicant_arm_command import ReplicantArmCommand
from tdw.replicant.arm import Arm


class ReplicantArmMotionCommand(ReplicantArmCommand, ABC):
    """
    These commands involve the motion of a Replicant's arm.
    """

    def __init__(self, id: int, arm: Arm, duration: float):
        """
        :param id: The unique object ID.
        :param arm: The arm doing the action.
        :param duration: The duration of the motion in seconds.
        """

        super().__init__(arm=arm, id=id)
        """:field
        The duration of the motion in seconds.
        """
        self.duration: float = duration
