# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.replicant_look_at_command import ReplicantLookAtCommand


class ReplicantRotateHeadBy(ReplicantLookAtCommand):
    """
    Rotate the Replicant's head by an angle around an axis.
    """

    def __init__(self, id: int, angle: float, axis: str = "yaw", duration: float = 0.1, set_status: bool = True):
        """
        :param id: The unique object ID.
        :param angle: The angle of rotation in degrees.
        :param axis: The axis of rotation.
        :param duration: The duration of the motion.
        :param set_status: If True, when this command ends, it will set the Replicant output data's status.
        """

        super().__init__(duration=duration, set_status=set_status, id=id)
        """:field
        The axis of rotation.
        """
        self.axis: str = axis
        """:field
        The angle of rotation in degrees.
        """
        self.angle: float = angle
