# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.replicant_base_command import ReplicantBaseCommand


class ReplicantLookAtCommand(ReplicantBaseCommand, ABC):
    """
    These commands tell a Replicant to look at a target position or object.
    """

    def __init__(self, id: int, duration: float = 0.1, set_status: bool = True):
        """
        :param id: The unique object ID.
        :param duration: The duration of the motion.
        :param set_status: If True, when this command ends, it will set the Replicant output data's status.
        """

        super().__init__(id=id)
        """:field
        The duration of the motion.
        """
        self.duration: float = duration
        """:field
        If True, when this command ends, it will set the Replicant output data's status.
        """
        self.set_status: bool = set_status
