# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.replicant_base_command import ReplicantBaseCommand


class ReplicantStep(ReplicantBaseCommand):
    """
    Advance the Replicant's IK solvers by 1 frame.
    """

    def __init__(self, id: int):
        """
        :param id: The unique object ID.
        """

        super().__init__(id=id)

