# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.replicant_look_at_command import ReplicantLookAtCommand


class ReplicantLookAtObject(ReplicantLookAtCommand):
    """
    Tell the Replicant to start to look at an object.
    """

    def __init__(self, id: int, object_id: int, use_centroid: bool = True, duration: float = 0.1, set_status: bool = True):
        """
        :param id: The unique object ID.
        :param object_id: The ID of the target object.
        :param use_centroid: If True, look at the centroid of the object. If False, look at the position of the object (y=0).
        :param duration: The duration of the motion.
        :param set_status: If True, when this command ends, it will set the Replicant output data's status.
        """

        super().__init__(duration=duration, set_status=set_status, id=id)
        """:field
        The ID of the target object.
        """
        self.object_id: int = object_id
        """:field
        If True, look at the centroid of the object. If False, look at the position of the object (y=0).
        """
        self.use_centroid: bool = use_centroid
