# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.replicant_base_arm_command import ReplicantBaseArmCommand
from tdw.replicant.arm import Arm


class ReplicantGraspObject(ReplicantBaseArmCommand):
    """
    Grasp a target object.
    """

    def __init__(self, id: int, arm: Arm, offset: float, object_id: int, set_status: bool = True):
        """
        :param id: The unique object ID.
        :param arm: The arm doing the action.
        :param offset: Offset the object from the hand by this distance.
        :param object_id: The target object ID.
        :param set_status: If True, when this command ends, it will set the Replicant output data's status.
        """

        super().__init__(arm=arm, id=id)
        """:field
        The target object ID.
        """
        self.object_id: int = object_id
        """:field
        If True, when this command ends, it will set the Replicant output data's status.
        """
        self.set_status: bool = set_status
        """:field
        Offset the object from the hand by this distance.
        """
        self.offset: float = offset
