# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.replicant_base_arm_command import ReplicantBaseArmCommand
from tdw.replicant.arm import Arm


class ReplicantDropObject(ReplicantBaseArmCommand):
    """
    Drop a held object.
    """

    def __init__(self, id: int, arm: Arm, offset_distance: float = 0.1, set_status: bool = True):
        """
        :param id: The unique object ID.
        :param arm: The arm doing the action.
        :param offset_distance: Prior to being dropped, the object will be moved by this distance along its forward directional vector.
        :param set_status: If True, when this command ends, it will set the Replicant output data's status.
        """

        super().__init__(arm=arm, id=id)
        """:field
        Prior to being dropped, the object will be moved by this distance along its forward directional vector.
        """
        self.offset_distance: float = offset_distance
        """:field
        If True, when this command ends, it will set the Replicant output data's status.
        """
        self.set_status: bool = set_status
