# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_command import ObjectCommand
from typing import Dict


class RotateObjectToEulerAngles(ObjectCommand):
    """
    Set the rotation of the object with Euler angles.
    """

    def __init__(self, id: int, euler_angles: Dict[str, float], use_centroid: bool = False):
        """
        :param id: The unique object ID.
        :param euler_angles: The new Euler angles of the object.
        :param use_centroid: If false, rotate around the bottom-center position of the object. If true, rotate around the bottom-center position of the object and then teleport the object to its centroid (such that it rotates around the centroid).
        """

        super().__init__(id=id)
        """:field
        The new Euler angles of the object.
        """
        self.euler_angles: Dict[str, float] = euler_angles
        """:field
        If false, rotate around the bottom-center position of the object. If true, rotate around the bottom-center position of the object and then teleport the object to its centroid (such that it rotates around the centroid).
        """
        self.use_centroid: bool = use_centroid
