# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.sensor_container_command import SensorContainerCommand


class RotateSensorContainerBy(SensorContainerCommand):
    """
    Rotate the sensor container of the avatar by a given angle along a given axis.
    """

    def __init__(self, angle: float, axis: str, sensor_name: str = "SensorContainer", avatar_id: str = "a"):
        """
        :param angle: The angle of rotation.
        :param axis: The axis of rotation.
        :param sensor_name: The name of the target sensor.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(sensor_name=sensor_name, avatar_id=avatar_id)
        """:field
        The axis of rotation.
        """
        self.axis: str = axis
        """:field
        The angle of rotation.
        """
        self.angle: float = angle
