# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.avatar_command import AvatarCommand
from typing import Dict


class RotateAvatarToEulerAngles(AvatarCommand):
    """
    Set the rotation of the avatar with Euler angles.
    """

    def __init__(self, euler_angles: Dict[str, float], avatar_id: str = "a"):
        """
        :param euler_angles: The new Euler angles of the avatar.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(avatar_id=avatar_id)
        """:field
        The new Euler angles of the avatar.
        """
        self.euler_angles: Dict[str, float] = euler_angles
