# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_command import ObjectCommand


class RotateObjectBy(ObjectCommand):
    """
    Rotate an object by a given angle around a given axis.
    """

    def __init__(self, id: int, angle: float, axis: str = "yaw", is_world: bool = True, use_centroid: bool = False):
        """
        :param id: The unique object ID.
        :param angle: The angle of rotation in degrees.
        :param axis: The axis of rotation.
        :param is_world: If True, the object will rotate around global axes. If False, the object will around local axes. Ignored if use_centroid == True.
        :param use_centroid: If True, rotate around the object's centroid. If False, rotate around the bottom-center position of the object.
        """

        super().__init__(id=id)
        """:field
        The axis of rotation.
        """
        self.axis: str = axis
        """:field
        The angle of rotation in degrees.
        """
        self.angle: float = angle
        """:field
        If True, the object will rotate around global axes. If False, the object will around local axes. Ignored if use_centroid == True.
        """
        self.is_world: bool = is_world
        """:field
        If True, rotate around the object's centroid. If False, rotate around the bottom-center position of the object.
        """
        self.use_centroid: bool = use_centroid
