# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.rotate_sensor_container_towards import RotateSensorContainerTowards


class RotateSensorContainerTowardsObject(RotateSensorContainerTowards):
    """
    Rotate the sensor container towards the current position of a target object.
    """

    def __init__(self, object_id: int, use_centroid: bool = True, speed: float = 3, sensor_name: str = "SensorContainer", avatar_id: str = "a"):
        """
        :param object_id: The ID of the object we want the sensor container to rotate towards.
        :param use_centroid: If true, rotate towards the centroid of the object. If false, rotate towards the position of the object (y=0).
        :param speed: The maximum angular speed that the sensor container will rotate per frame.
        :param sensor_name: The name of the target sensor.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(speed=speed, sensor_name=sensor_name, avatar_id=avatar_id)
        """:field
        The ID of the object we want the sensor container to rotate towards.
        """
        self.object_id: int = object_id
        """:field
        If true, rotate towards the centroid of the object. If false, rotate towards the position of the object (y=0).
        """
        self.use_centroid: bool = use_centroid
