# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.rotate_sensor_container_towards import RotateSensorContainerTowards
from typing import Dict


class RotateSensorContainerTowardsRotation(RotateSensorContainerTowards):
    """
    Rotate the sensor container towards a target rotation.
    """

    def __init__(self, rotation: Dict[str, float] = None, speed: float = 3, sensor_name: str = "SensorContainer", avatar_id: str = "a"):
        """
        :param rotation: The target rotation.
        :param speed: The maximum angular speed that the sensor container will rotate per frame.
        :param sensor_name: The name of the target sensor.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(speed=speed, sensor_name=sensor_name, avatar_id=avatar_id)
        if rotation is None:
            """:field
            The target rotation.
            """
            self.rotation: Dict[str, float] = {"x": 0, "y": 0, "z": 0, "w": 1}
        else:
            self.rotation = rotation
