# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.avatar_command import AvatarCommand
from typing import Dict


class RotateAvatarTo(AvatarCommand):
    """
    Set the rotation quaternion of the avatar.
    """

    def __init__(self, rotation: Dict[str, float], avatar_id: str = "a"):
        """
        :param rotation: The rotation quaternion.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(avatar_id=avatar_id)
        """:field
        The rotation quaternion.
        """
        self.rotation: Dict[str, float] = rotation
