# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command


class RotateHdriSkyboxBy(Command):
    """
    Rotate the HDRI skybox by a given value and the sun light by the same value in the opposite direction, to maintain alignment.
    """

    def __init__(self, angle: float):
        """
        :param angle: The value to rotate the HDRI skybox by. Skyboxes are always rotated in a positive direction; values are clamped between 0 and 360, and any negative values are forced positive. Rotate around the pitch axis to set the elevation of the sun. Rotate around the yaw axis to set the angle of the sun.
        """

        super().__init__()
        """:field
        The value to rotate the HDRI skybox by. Skyboxes are always rotated in a positive direction; values are clamped between 0 and 360, and any negative values are forced positive. Rotate around the pitch axis to set the elevation of the sun. Rotate around the yaw axis to set the angle of the sun.
        """
        self.angle: float = angle
