# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.sensor_container_command import SensorContainerCommand


class RotateSensorContainerTowards(SensorContainerCommand, ABC):
    """
    These commands rotate the sensor container towards a target by a given angular speed per frame.
    """

    def __init__(self, speed: float = 3, sensor_name: str = "SensorContainer", avatar_id: str = "a"):
        """
        :param speed: The maximum angular speed that the sensor container will rotate per frame.
        :param sensor_name: The name of the target sensor.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(sensor_name=sensor_name, avatar_id=avatar_id)
        """:field
        The maximum angular speed that the sensor container will rotate per frame.
        """
        self.speed: float = speed
