# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.adjust_visual_effect_command import AdjustVisualEffectCommand
from typing import Dict


class RotateVisualEffectTo(AdjustVisualEffectCommand):
    """
    Set the rotation of a non-physical visual effect.
    """

    def __init__(self, id: int, rotation: Dict[str, float]):
        """
        :param id: The ID of the non-physics object.
        :param rotation: The rotation quaternion.
        """

        super().__init__(id=id)
        """:field
        The rotation quaternion.
        """
        self.rotation: Dict[str, float] = rotation
