# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.send_single_data_command import SendSingleDataCommand
from typing import List


class SendObjectsDataCommand(SendSingleDataCommand, ABC):
    """
    These commands send data about cached objects (models, avatars, etc.)
    """

    def __init__(self, ids: List[int], frequency: str = "once"):
        """
        :param ids: The IDs of the objects. If this list is undefined or empty, the build will return data for all objects.
        :param frequency: The frequency at which data is sent.
        """

        super().__init__(frequency=frequency)
        """:field
        The IDs of the objects. If this list is undefined or empty, the build will return data for all objects.
        """
        self.ids: List[int] = ids
