# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_overlap_command import SendOverlapCommand
from typing import Dict


class SendOverlapBox(SendOverlapCommand):
    """
    Check which objects a box-shaped space overlaps with.
    """

    def __init__(self, position: Dict[str, float], rotation: Dict[str, float], half_extents: Dict[str, float], id: int = 0):
        """
        :param position: The center of the shape.
        :param rotation: The rotation of the box.
        :param half_extents: Half of the extents of the box (i.e. half the scale of an object).
        :param id: The ID of the output data object. This can be used to match the output data back to the command that created it.
        """

        super().__init__(position=position, id=id)
        """:field
        Half of the extents of the box (i.e. half the scale of an object).
        """
        self.half_extents: Dict[str, float] = half_extents
        """:field
        The rotation of the box.
        """
        self.rotation: Dict[str, float] = rotation
