# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_data_command import SendDataCommand


class SendContainment(SendDataCommand):
    """
    Send containment data using container shapes. See: `add_box_container`, `add_cylinder_container`, and `add_sphere_container`. Container shapes will check for overlaps with other objects.
    """

    def __init__(self, frequency: str = "once"):
        """
        :param frequency: The frequency at which data is sent.
        """

        super().__init__(frequency=frequency)

