# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.send_data_command import SendDataCommand


class SendFixedLengthDataCommand(SendDataCommand, ABC):
    """
    These commands send fixed-length data, meaning that the output byte array size is always the same if the send frequency is "always". The output byte array is resized whenever these commands are sent. This means that these commands are significantly slower if they are sent per-communicate call with frequency "once".
    """

    def __init__(self, frequency: str = "once"):
        """
        :param frequency: The frequency at which data is sent.
        """

        super().__init__(frequency=frequency)

