# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_raycast_command import SendRaycastCommand
from typing import Dict


class SendBoxcast(SendRaycastCommand):
    """
    Cast a box along a direction and return the results. The can be multiple hits, each of which will be sent to the controller as Raycast data.
    """

    def __init__(self, half_extents: Dict[str, float], origin: Dict[str, float] = None, destination: Dict[str, float] = None, id: int = 0):
        """
        :param half_extents: The half-extents of the box.
        :param origin: The origin of the raycast.
        :param destination: The destination of the raycast.
        :param id: The ID of the output data object. This can be used to match the output data back to the command that created it.
        """

        super().__init__(origin=origin, destination=destination, id=id)
        """:field
        The half-extents of the box.
        """
        self.half_extents: Dict[str, float] = half_extents
