# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_fixed_length_avatars_data_command import SendFixedLengthAvatarsDataCommand
from typing import List


class SendFastImageSensors(SendFixedLengthAvatarsDataCommand):
    """
    Send the and rotation of each avatar's camera in the scene. This is slightly faster than SendImageSensors, and FastImageSensors compresses much better than ImageSensors. However, FastImageSensors is missing a lot of information contained in ImageSensors, including avatar IDs, making it harder to use. See: send_avatar_ids which serializes the avatar IDs in the same order as the data in FastImageSensors.
    """

    def __init__(self, ids: List[str] = None, frequency: str = "once"):
        """
        :param ids: The avatar IDs. If empty, data for all avatars in the scene will be sent.
        :param frequency: The frequency at which data is sent.
        """

        super().__init__(ids=ids, frequency=frequency)

