# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.send_fixed_length_data_command import SendFixedLengthDataCommand
from typing import List


class SendFixedLengthObjectDataCommand(SendFixedLengthDataCommand, ABC):
    """
    Abstract base class for sending object data where the size of the output data is the same on every communicate call.
    """

    def __init__(self, ids: List[int] = None, frequency: str = "once"):
        """
        :param ids: Send data for objects with these IDs. If this is empty, data for all objects will be sent.
        :param frequency: The frequency at which data is sent.
        """

        super().__init__(frequency=frequency)
        if ids is None:
            """:field
            Send data for objects with these IDs. If this is empty, data for all objects will be sent.
            """
            self.ids: List[int] = [0]
        else:
            self.ids = ids
