# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_data_command import SendDataCommand


class SendRobotJointVelocities(SendDataCommand):
    """
    Send velocity data for each joint of each robot in the scene. This is separate from DynamicRobots output data for the sake of speed in certain simulations.
    """

    def __init__(self, frequency: str = "once"):
        """
        :param frequency: The frequency at which data is sent.
        """

        super().__init__(frequency=frequency)

