# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_vr_command import SendVrCommand


class SendOculusTouchButtons(SendVrCommand):
    """
    Send data for buttons pressed on Oculus Touch controllers.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
