# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_vr_command import SendVrCommand


class SendStaticOculusTouch(SendVrCommand):
    """
    Send static data for the Oculus Touch rig.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
