# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.add_material_command import AddMaterialCommand


class SendMaterialReport(AddMaterialCommand):
    """
    Tell the build to send a report of a material asset bundle. Each report will be a separate LogMessage.
    """

    def __init__(self, url: str, name: str):
        """
        :param url: The location of the asset bundle. If the asset bundle is remote, this must be a valid URL. If the asset is a local file, this must begin with the prefix "file:///"
        :param name: The name of the asset bundle.
        """

        super().__init__(name=name, url=url)

