# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.command import Command


class SendMultipleDataOnceCommand(Command, ABC):
    """
    These commands send data exactly once to the controller (not per-frame). Unlike most output data such as Tranforms, there can be more than one output data object of this type in the build's response. For example, the build can send multiple Raycast objects in the same list.
    """

    def __init__(self, id: int = 0):
        """
        :param id: The ID of the output data object. This can be used to match the output data back to the command that created it.
        """

        super().__init__()
        """:field
        The ID of the output data object. This can be used to match the output data back to the command that created it.
        """
        self.id: int = id
