# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_data_command import SendDataCommand
from typing import List


class SendColliderIntersections(SendDataCommand):
    """
    Send data for collider intersections between pairs of objects and between single objects and the environment (e.g. walls). Note that each intersection is a separate output data object, and that each pair of objects/environment meshes might intersect more than once because they might have more than one collider.
    """

    def __init__(self, obj_intersection_ids: List[List[int]] = None, env_intersection_ids: List[int] = None, frequency: str = "once"):
        """
        :param obj_intersection_ids: Pairs of object IDs, for example <computeroutput>[[0, 1], [0, 2]]</computeroutput>. Object IDs pairs in this array will be tested for collider intersections with each other.
        :param env_intersection_ids: A one-dimensional list of object IDs, for example <computeroutput>[0, 1, 2]</computeroutput>. Object IDs in this list will be tested for collider intersections with the environment.
        :param frequency: The frequency at which data is sent.
        """

        super().__init__(frequency=frequency)
        if obj_intersection_ids is None:
            """:field
            Pairs of object IDs, for example <computeroutput>[[0, 1], [0, 2]]</computeroutput>. Object IDs pairs in this array will be tested for collider intersections with each other.
            """
            self.obj_intersection_ids: List[List[int]] = list()
        else:
            self.obj_intersection_ids = obj_intersection_ids
        if env_intersection_ids is None:
            """:field
            A one-dimensional list of object IDs, for example <computeroutput>[0, 1, 2]</computeroutput>. Object IDs in this list will be tested for collider intersections with the environment.
            """
            self.env_intersection_ids: List[int] = [0]
        else:
            self.env_intersection_ids = env_intersection_ids
