# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_raycast_command import SendRaycastCommand
from typing import Dict


class SendMouseRaycast(SendRaycastCommand):
    """
    Raycast from a camera through the mouse screen position.
    """

    def __init__(self, avatar_id: str = "a", origin: Dict[str, float] = None, destination: Dict[str, float] = None, id: int = 0):
        """
        :param avatar_id: The ID of the avatar of the rendering camera.
        :param origin: The origin of the raycast.
        :param destination: The destination of the raycast.
        :param id: The ID of the output data object. This can be used to match the output data back to the command that created it.
        """

        super().__init__(origin=origin, destination=destination, id=id)
        """:field
        The ID of the avatar of the rendering camera.
        """
        self.avatar_id: str = avatar_id
