# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.add_model_command import AddModelCommand
from typing import Dict, List


class SendModelReport(AddModelCommand):
    """
    Tell the build to send a report of a model asset bundle. Each report will be a separate LogMessage.
    """

    def __init__(self, url: str, name: str, id: int, flex: bool, scale_factor: float = 1, category: str = "", affordance_points: List[Dict[str, float]] = None):
        """
        :param url: The location of the asset bundle. If the asset bundle is remote, this must be a valid URL. If the asset is a local file, this must begin with the prefix "file:///"
        :param name: The name of the asset bundle.
        :param id: The unique ID of the object.
        :param flex: If True, we expect this model to be Flex-compatible.
        :param scale_factor: The default scale factor of a model.
        :param category: The model category.
        :param affordance_points: A list of affordance points. Can be empty.
        """

        super().__init__(id=id, scale_factor=scale_factor, category=category, affordance_points=affordance_points, name=name, url=url)
        """:field
        If True, we expect this model to be Flex-compatible.
        """
        self.flex: bool = flex
