# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_data_command import SendDataCommand
from typing import List


class SendOccupancyMap(SendDataCommand):
    """
    Request an occupancy map, which will divide the environment into a grid with values indicating whether each cell is occupied or free.
    """

    def __init__(self, cell_size: float = 0.5, raycast_y: float = 2.5, ignore_objects: List[int] = None, frequency: str = "once"):
        """
        :param cell_size: The size of each cell in meters.
        :param raycast_y: When calculating the occupancy map, rays will be cast from this height in meters.
        :param ignore_objects: Object IDs in this array won't cause a cell to be marked as occupied.
        :param frequency: The frequency at which data is sent.
        """

        super().__init__(frequency=frequency)
        """:field
        The size of each cell in meters.
        """
        self.cell_size: float = cell_size
        """:field
        When calculating the occupancy map, rays will be cast from this height in meters.
        """
        self.raycast_y: float = raycast_y
        if ignore_objects is None:
            """:field
            Object IDs in this array won't cause a cell to be marked as occupied.
            """
            self.ignore_objects: List[int] = [0]
        else:
            self.ignore_objects = ignore_objects
