# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_fixed_length_avatars_data_command import SendFixedLengthAvatarsDataCommand
from typing import List


class SendAvatarIds(SendFixedLengthAvatarsDataCommand):
    """
    Send the IDs of each avatar in the scene.
    """

    def __init__(self, ids: List[str] = None, frequency: str = "once"):
        """
        :param ids: The avatar IDs. If empty, data for all avatars in the scene will be sent.
        :param frequency: The frequency at which data is sent.
        """

        super().__init__(ids=ids, frequency=frequency)

