# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.send_vr_command import SendVrCommand


class SendLeapMotion(SendVrCommand):
    """
    Send Leap Motion hand tracking data.
    """

    def __init__(self, max_num_collisions_per_bone: int = 5):
        """
        :param max_num_collisions_per_bone: The maximum number of collisions per bone that will be returned in the output data.
        """

        super().__init__()
        """:field
        The maximum number of collisions per bone that will be returned in the output data.
        """
        self.max_num_collisions_per_bone: int = max_num_collisions_per_bone
