# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.avatar_command import AvatarCommand


class SensorContainerCommand(AvatarCommand, ABC):
    """
    These commands adjust an avatar's image sensor container. All avatars have at least one sensor, which is named "SensorContainer". Sticky Mitten Avatars have an additional sensor named "FollowCamera". For a list of all image sensors attached to an avatar, send send_image_sensors.
    """

    def __init__(self, sensor_name: str = "SensorContainer", avatar_id: str = "a"):
        """
        :param sensor_name: The name of the target sensor.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(avatar_id=avatar_id)
        """:field
        The name of the target sensor.
        """
        self.sensor_name: str = sensor_name
