# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.floor_command import FloorCommand


class SetFloorMaterial(FloorCommand):
    """
    Set the material of the floor.
    """

    def __init__(self, name: str):
        """
        :param name: The name of the material. The material must already be loaded in memory.
        """

        super().__init__()
        """:field
        The name of the material. The material must already be loaded in memory.
        """
        self.name: str = name
