# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.robot_command import RobotCommand
from typing import Dict


class SetRobotColor(RobotCommand):
    """
    Set the visual color of a robot in the scene.
    """

    def __init__(self, color: Dict[str, float], id: int = 0):
        """
        :param color: The new color of the robot.
        :param id: The ID of the robot in the scene.
        """

        super().__init__(id=id)
        """:field
        The new color of the robot.
        """
        self.color: Dict[str, float] = color
