# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.sub_object_command import SubObjectCommand


class SetSubObjectLight(SubObjectCommand):
    """
    Turn a light on or off.
    """

    def __init__(self, id: int, is_on: bool):
        """
        :param id: The unique object ID.
        :param is_on: If true, the light will be on.
        """

        super().__init__(id=id)
        """:field
        If true, the light will be on.
        """
        self.is_on: bool = is_on
