# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.post_process_command import PostProcessCommand


class SetSaturation(PostProcessCommand):
    """
    Set the saturation value of the post-processing color grading.
    """

    def __init__(self, saturation: float = -20):
        """
        :param saturation: The saturation of the post-processing.
        """

        super().__init__()
        """:field
        The saturation of the post-processing.
        """
        self.saturation: float = saturation
