# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.sub_object_command import SubObjectCommand


class SetMotorForce(SubObjectCommand):
    """
    Set the force a motor.
    """

    def __init__(self, id: int, force: float):
        """
        :param id: The unique object ID.
        :param force: The force of the motor.
        """

        super().__init__(id=id)
        """:field
        The force of the motor.
        """
        self.force: float = force
