# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.sensor_container_command import SensorContainerCommand


class SetRenderOrder(SensorContainerCommand):
    """
    Set the order in which this camera will render relative to other cameras in the scene. This can prevent flickering on the screen when there are multiple cameras. This doesn't affect image capture; it only affects what the simulation application screen is displaying at runtime.
    """

    def __init__(self, render_order: int = 0, sensor_name: str = "SensorContainer", avatar_id: str = "a"):
        """
        :param render_order: The render order. The highest number will the be camera rendered in the application window. By default, all TDW cameras have the same render order number.
        :param sensor_name: The name of the target sensor.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(sensor_name=sensor_name, avatar_id=avatar_id)
        """:field
        The render order. The highest number will the be camera rendered in the application window. By default, all TDW cameras have the same render order number.
        """
        self.render_order: int = render_order
