# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command


class SetDspBufferSize(Command):
    """
    Set the DSP buffer size. A lower value will result in less latency.
    """

    def __init__(self, size: int = 1024):
        """
        :param size: The DSP buffer size.
        """

        super().__init__()
        """:field
        The DSP buffer size.
        """
        self.size: int = size
