# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.object_command import ObjectCommand


class SetFlexActor(ObjectCommand, ABC):
    """
    These commands create a new FlexActor of type T with a FlexAsset of type U, or to modify an object that already has a component of type T. This command must be sent before applying any other Flex commands to an object. You probably will want to send set_kinematic_state prior to sending this command.
    """

    def __init__(self, id: int, mass_scale: float = 1, draw_particles: bool = False):
        """
        :param id: The unique object ID.
        :param mass_scale: The mass scale factor.
        :param draw_particles: Debug drawing of particles.
        """

        super().__init__(id=id)
        """:field
        The mass scale factor.
        """
        self.mass_scale: float = mass_scale
        """:field
        Debug drawing of particles.
        """
        self.draw_particles: bool = draw_particles
