# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.flex_object_command import FlexObjectCommand


class SetFlexObjectMass(FlexObjectCommand):
    """
    Set the mass of the Flex object. The mass is distributed equally across all particles. Thus the particle mass equals mass divided by number of particles.
    """

    def __init__(self, id: int, mass: float):
        """
        :param id: The unique object ID.
        :param mass: Set the mass of the Flex object to this value.
        """

        super().__init__(id=id)
        """:field
        Set the mass of the Flex object to this value.
        """
        self.mass: float = mass
