# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_command import ObjectCommand


class SetVrGraspable(ObjectCommand):
    """
    Make an object graspable for a VR rig, with Oculus touch controllers. Uses the AutoHand plugin for grasping and physics interaction behavior.
    """

    def __init__(self, id: int, joint_break_force: float = 3500):
        """
        :param id: The unique object ID.
        :param joint_break_force: The joint break force for this graspable object. Lower values mean it's easier to break the joint.
        """

        super().__init__(id=id)
        """:field
        The joint break force for this graspable object. Lower values mean it's easier to break the joint.
        """
        self.joint_break_force: float = joint_break_force
