# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.drone_command import DroneCommand


class SetDroneSpeed(DroneCommand):
    """
    Set the forward and/or backward speed of the drone.
    """

    def __init__(self, id: int, forward_speed: float = 3.0, backward_speed: float = 3.0):
        """
        :param id: The unique object ID.
        :param forward_speed: The drone's max forward speed.
        :param backward_speed: The drone's max backward speed.
        """

        super().__init__(id=id)
        """:field
        The drone's max forward speed.
        """
        self.forward_speed: float = forward_speed
        """:field
        The drone's max backward speed.
        """
        self.backward_speed: float = backward_speed
