# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.obi_fluid_command import ObiFluidCommand


class SetObiFluidLifespan(ObiFluidCommand):
    """
    Set a fluid emitter's particle lifespan.
    """

    def __init__(self, id: int, lifespan: float = 4):
        """
        :param id: The unique object ID.
        :param lifespan: The particle lifespan in seconds.
        """

        super().__init__(id=id)
        """:field
        The particle lifespan in seconds.
        """
        self.lifespan: float = lifespan
