# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.set_robot_joint_position_command import SetRobotJointPositionCommand


class SetPrismaticPosition(SetRobotJointPositionCommand):
    """
    Instantaneously set the position of a prismatic joint. Only use this command to set an initial pose for a robot.
    """

    def __init__(self, joint_id: int, position: float, id: int = 0):
        """
        :param joint_id: The ID of the joint.
        :param position: The position in meters.
        :param id: The ID of the robot in the scene.
        """

        super().__init__(joint_id=joint_id, id=id)
        """:field
        The position in meters.
        """
        self.position: float = position
