# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.set_robot_joint_position_command import SetRobotJointPositionCommand
from typing import Dict


class SetSphericalAngles(SetRobotJointPositionCommand):
    """
    Instantaneously set the angles of a spherical joint. Only use this command to set an initial pose for a robot.
    """

    def __init__(self, joint_id: int, angles: Dict[str, float], id: int = 0):
        """
        :param joint_id: The ID of the joint.
        :param angles: The angles in degrees.
        :param id: The ID of the robot in the scene.
        """

        super().__init__(joint_id=joint_id, id=id)
        """:field
        The angles in degrees.
        """
        self.angles: Dict[str, float] = angles
