# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_type_command import ObjectTypeCommand


class SetKinematicState(ObjectTypeCommand):
    """
    Set an object's Rigidbody to be kinematic or not. A kinematic object won't respond to PhysX physics.
    """

    def __init__(self, id: int, is_kinematic: bool = False, use_gravity: bool = False):
        """
        :param id: The unique object ID.
        :param is_kinematic: If True, the Rigidbody will be kinematic, and won't respond to physics.
        :param use_gravity: If True, the object will respond to gravity.
        """

        super().__init__(id=id)
        """:field
        If True, the Rigidbody will be kinematic, and won't respond to physics.
        """
        self.is_kinematic: bool = is_kinematic
        """:field
        If True, the object will respond to gravity.
        """
        self.use_gravity: bool = use_gravity
