# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.avatar_type_command import AvatarTypeCommand


class SetFirstPersonAvatar(AvatarTypeCommand):
    """
    Set the parameters of an A_First_Person avatar.
    """

    def __init__(self, height: float = 1.6, camera_height: float = 1.4, radius: float = 0.5, slope_limit: float = 15, detect_collisions: bool = True, move_speed: float = 1.5, look_speed: float = 50, look_x_limit: float = 45, avatar_id: str = "a"):
        """
        :param height: The height of the avatar.
        :param camera_height: The height of the camera.
        :param radius: The radius of the avatar.
        :param slope_limit: The avatar can only climb slopes up to this many degrees.
        :param detect_collisions: If True, the avatar will collide with other objects.
        :param move_speed: The move speed in meters per second.
        :param look_speed: The camera rotation speed in degrees per second.
        :param look_x_limit: The camera rotation limit around the x axis in degrees.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(avatar_id=avatar_id)
        """:field
        The height of the avatar.
        """
        self.height: float = height
        """:field
        The height of the camera.
        """
        self.camera_height: float = camera_height
        """:field
        The radius of the avatar.
        """
        self.radius: float = radius
        """:field
        The avatar can only climb slopes up to this many degrees.
        """
        self.slope_limit: float = slope_limit
        """:field
        If True, the avatar will collide with other objects.
        """
        self.detect_collisions: bool = detect_collisions
        """:field
        The move speed in meters per second.
        """
        self.move_speed: float = move_speed
        """:field
        The camera rotation speed in degrees per second.
        """
        self.look_speed: float = look_speed
        """:field
        The camera rotation limit around the x axis in degrees.
        """
        self.look_x_limit: float = look_x_limit
