# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.obi_fluid_command import ObiFluidCommand


class SetObiFluidRandomVelocity(ObiFluidCommand):
    """
    Set a fluid emitter's random velocity.
    """

    def __init__(self, id: int, random_velocity: float = 0):
        """
        :param id: The unique object ID.
        :param random_velocity: Random velocity of emitted particles.
        """

        super().__init__(id=id)
        """:field
        Random velocity of emitted particles.
        """
        self.random_velocity: float = random_velocity
