# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_type_command import ObjectTypeCommand


class SetPrimitiveVisualMaterial(ObjectTypeCommand):
    """
    Set the material of an object created via load_primitive_from_resources
    """

    def __init__(self, id: int, name: str):
        """
        :param id: The unique object ID.
        :param name: The name of the material.
        """

        super().__init__(id=id)
        """:field
        The name of the material.
        """
        self.name: str = name
