# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.proc_gen_room_command import ProcGenRoomCommand


class SetProcGenCeilingHeight(ProcGenRoomCommand):
    """
    Set the height of all ceiling tiles in a proc-gen room.
    """

    def __init__(self, height: float = 2.85):
        """
        :param height: The y value of all ceiling tiles.
        """

        super().__init__()
        """:field
        The y value of all ceiling tiles.
        """
        self.height: float = height
