# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.adjust_textured_quad_command import AdjustTexturedQuadCommand
from typing import Dict


class SetTexturedQuad(AdjustTexturedQuadCommand):
    """
    Apply a texture to a pre-existing quad.
    """

    def __init__(self, id: int, image: str, dimensions: Dict[str, int]):
        """
        :param id: The ID of the non-physics object.
        :param image: base64 string representation of the image byte array.
        :param dimensions: The expected dimensions of the image in pixels.
        """

        super().__init__(id=id)
        """:field
        The expected dimensions of the image in pixels.
        """
        self.dimensions: Dict[str, int] = dimensions
        """:field
        base64 string representation of the image byte array.
        """
        self.image: str = image
