# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.sub_object_command import SubObjectCommand


class SetSpringTargetPosition(SubObjectCommand):
    """
    Set the target position of a spring.
    """

    def __init__(self, id: int, target_position: float):
        """
        :param id: The unique object ID.
        :param target_position: The target position of the spring, expressed as degrees in a circle.
        """

        super().__init__(id=id)
        """:field
        The target position of the spring, expressed as degrees in a circle.
        """
        self.target_position: float = target_position
