# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.global_boolean_command import GlobalBooleanCommand


class SetPostProcess(GlobalBooleanCommand):
    """
    Toggle whether post-processing is enabled in the scene. Disabling post-processing will make rendered images "flatter". Initial value = True (post-processing is enabled)
    """

    def __init__(self, value: bool):
        """
        :param value: Boolean value.
        """

        super().__init__(value=value)

