# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.obi_fluid_fluid_command import ObiFluidFluidCommand


class SetObiFluidSmoothing(ObiFluidFluidCommand):
    """
    Set a fluid's smoothing value.
    """

    def __init__(self, id: int, smoothing: float):
        """
        :param id: The unique object ID.
        :param smoothing: A percentage of the particle radius used to define the radius of the zone around each particle when calculating fluid density. Larger values will create smoother fluids, which are also less performant.
        """

        super().__init__(id=id)
        """:field
        A percentage of the particle radius used to define the radius of the zone around each particle when calculating fluid density. Larger values will create smoother fluids, which are also less performant.
        """
        self.smoothing: float = smoothing
