# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command


class SetSleepThreshold(Command):
    """
    Set the global Rigidbody "sleep threshold", the mass-normalized energy threshold below which objects start going to sleep. A "sleeping" object is completely still until moved again by a force (object impact, force command, etc.)
    """

    def __init__(self, sleep_threshold: float = 0.005):
        """
        :param sleep_threshold: When any object's speed is less than this number, it will go to "sleep" and stop moving.
        """

        super().__init__()
        """:field
        When any object's speed is less than this number, it will go to "sleep" and stop moving.
        """
        self.sleep_threshold: float = sleep_threshold
