# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.wheelchair_replicant_command import WheelchairReplicantCommand


class SetWheelchairMotorTorque(WheelchairReplicantCommand):
    """
    Set the motor torque of the wheelchair's rear wheels.
    """

    def __init__(self, id: int, right: float, left: float):
        """
        :param id: The unique object ID.
        :param right: The torque for the right rear wheel.
        :param left: The torque for the left rear wheel.
        """

        super().__init__(id=id)
        """:field
        The torque for the left rear wheel.
        """
        self.left: float = left
        """:field
        The torque for the right rear wheel.
        """
        self.right: float = right
