# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.proc_gen_walls_command import ProcGenWallsCommand
from typing import Dict, List


class SetProcGenWallsScale(ProcGenWallsCommand):
    """
    Set the scale of proc-gen wall sections.
    """

    def __init__(self, walls: List[Dict[str, float]], scale: Dict[str, float] = None):
        """
        :param walls: List of walls as (x, y) points on a grid.
        :param scale: The new scale of each wall section. By default, the scale of a wall section is (1, 1, 1).
        """

        super().__init__(walls=walls)
        if scale is None:
            """:field
            The new scale of each wall section. By default, the scale of a wall section is (1, 1, 1).
            """
            self.scale: Dict[str, float] = {"x": 1, "y": 1, "z": 1}
        else:
            self.scale = scale
