# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_type_command import ObjectTypeCommand


class SetSubObjectId(ObjectTypeCommand):
    """
    Set the ID of a composite sub-object. This can be useful when loading saved data that contains sub-object IDs. Note that the `id` parameter is for the parent object, not the sub-object. The sub-object is located via `sub_object_name`. Accordingly, this command only works when all of the names of a composite object's sub-objects are unique.
    """

    def __init__(self, id: int, sub_object_id: int, sub_object_name: str):
        """
        :param id: The unique object ID.
        :param sub_object_id: The new ID of the sub-object.
        :param sub_object_name: The expected name of the sub-object.
        """

        super().__init__(id=id)
        """:field
        The expected name of the sub-object.
        """
        self.sub_object_name: str = sub_object_name
        """:field
        The new ID of the sub-object.
        """
        self.sub_object_id: int = sub_object_id
