# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.robot_joint_target_command import RobotJointTargetCommand


class SetRevoluteTarget(RobotJointTargetCommand):
    """
    Set the target angle of a revolute robot joint. Per frame, the joint will revolve towards the target until it is either no longer possible to do so (i.e. due to physics) or because it has reached the target angle.
    """

    def __init__(self, joint_id: int, target: float, id: int = 0):
        """
        :param joint_id: The ID of the joint.
        :param target: The target angle in degrees.
        :param id: The ID of the robot in the scene.
        """

        super().__init__(joint_id=joint_id, id=id)
        """:field
        The target angle in degrees.
        """
        self.target: float = target
