# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.post_process_command import PostProcessCommand


class SetContrast(PostProcessCommand):
    """
    Set the contrast value of the post-processing color grading.
    """

    def __init__(self, contrast: float = 20):
        """
        :param contrast: The contrast of the post-processing.
        """

        super().__init__()
        """:field
        The contrast of the post-processing.
        """
        self.contrast: float = contrast
