# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command


class SetDownloadTimeout(Command):
    """
    Set the timeout after which an Asset Bundle Command (e.g. add_object) will retry a download. The default timeout is 30 minutes, which should always be sufficient. Send this command only if your computer or Internet connection is very slow.
    """

    def __init__(self, timeout: int = 1800, retry: bool = True):
        """
        :param timeout: The time in seconds until the asset bundle download request will timeout.
        :param retry: If true, if a download times out, the build will try to download it again.
        """

        super().__init__()
        """:field
        The time in seconds until the asset bundle download request will timeout.
        """
        self.timeout: int = timeout
        """:field
        If true, if a download times out, the build will try to download it again.
        """
        self.retry: bool = retry
