# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.sensor_container_command import SensorContainerCommand


class SetAntiAliasing(SensorContainerCommand):
    """
    Set the anti-aliasing mode for the avatar's camera.
    """

    def __init__(self, mode: str = "subpixel", sensor_name: str = "SensorContainer", avatar_id: str = "a"):
        """
        :param mode: The anti-aliasing mode.
        :param sensor_name: The name of the target sensor.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(sensor_name=sensor_name, avatar_id=avatar_id)
        """:field
        The anti-aliasing mode.
        """
        self.mode: str = mode
