# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_command import ObjectCommand


class SetObjectVisibility(ObjectCommand):
    """
    Toggle whether an object is visible. An invisible object will still have physics colliders and respond to physics events.
    """

    def __init__(self, id: int, visible: bool = True):
        """
        :param id: The unique object ID.
        :param visible: Toggles whether or not the object is visible.
        """

        super().__init__(id=id)
        """:field
        Toggles whether or not the object is visible.
        """
        self.visible: bool = visible
