# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.obi_fluid_command import ObiFluidCommand


class SetObiFluidResolution(ObiFluidCommand):
    """
    Set a fluid emitter's resolution.
    """

    def __init__(self, id: int, resolution: float):
        """
        :param id: The unique object ID.
        :param resolution: The size and amount of particles in 1 cubic meter. A value of 1 will use 1000 particles per cubic meter.
        """

        super().__init__(id=id)
        """:field
        The size and amount of particles in 1 cubic meter. A value of 1 will use 1000 particles per cubic meter.
        """
        self.resolution: float = resolution
