# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.wheelchair_replicant_command import WheelchairReplicantCommand


class SetWheelchairBrakeTorque(WheelchairReplicantCommand):
    """
    Set the brake torque of the wheelchair's wheels.
    """

    def __init__(self, id: int, torque: float):
        """
        :param id: The unique object ID.
        :param torque: The torque.
        """

        super().__init__(id=id)
        """:field
        The torque.
        """
        self.torque: float = torque
