# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.robot_joint_command import RobotJointCommand


class SetRobotJointFriction(RobotJointCommand):
    """
    Set the friction coefficient of a robot joint.
    """

    def __init__(self, joint_id: int, friction: float = 0.05, id: int = 0):
        """
        :param joint_id: The ID of the joint.
        :param friction: The friction coefficient.
        :param id: The ID of the robot in the scene.
        """

        super().__init__(joint_id=joint_id, id=id)
        """:field
        The friction coefficient.
        """
        self.friction: float = friction
