# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.sub_object_command import SubObjectCommand


class SetSpringDamper(SubObjectCommand):
    """
    Set the damper value of a spring.
    """

    def __init__(self, id: int, damper: float):
        """
        :param id: The unique object ID.
        :param damper: The damper value of the spring.
        """

        super().__init__(id=id)
        """:field
        The damper value of the spring.
        """
        self.damper: float = damper
