# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.robot_joint_command import RobotJointCommand


class SetRobotJointDrive(RobotJointCommand):
    """
    Set static joint drive parameters for a robot joint. Use the StaticRobot output data to determine which drives (x, y, and z) the joint has and what their default values are.
    """

    def __init__(self, joint_id: int, axis: str = "x", lower_limit: float = 0, upper_limit: float = 0, force_limit: float = 3, stiffness: float = 1000, damping: float = 300, id: int = 0):
        """
        :param joint_id: The ID of the joint.
        :param axis: The axis of the drive.
        :param lower_limit: The lower limit of the drive in degrees. If this and upper_limit are 0, the joint movement is unlimited.
        :param upper_limit: The upper limit of the drive in degrees. If this and lower_limit are 0, the joint movement is unlimited.
        :param force_limit: The force limit.
        :param stiffness: The stiffness of the drive.
        :param damping: The damping of the drive.
        :param id: The ID of the robot in the scene.
        """

        super().__init__(joint_id=joint_id, id=id)
        """:field
        The axis of the drive.
        """
        self.axis: str = axis
        """:field
        The lower limit of the drive in degrees. If this and upper_limit are 0, the joint movement is unlimited.
        """
        self.lower_limit: float = lower_limit
        """:field
        The upper limit of the drive in degrees. If this and lower_limit are 0, the joint movement is unlimited.
        """
        self.upper_limit: float = upper_limit
        """:field
        The force limit.
        """
        self.force_limit: float = force_limit
        """:field
        The stiffness of the drive.
        """
        self.stiffness: float = stiffness
        """:field
        The damping of the drive.
        """
        self.damping: float = damping
