# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.sub_object_command import SubObjectCommand


class SetHingeLimits(SubObjectCommand):
    """
    Set the angle limits of a hinge joint. This will work with hinges, motors, and springs.
    """

    def __init__(self, id: int, min_limit: float = 0, max_limit: float = 0):
        """
        :param id: The unique object ID.
        :param min_limit: The minimum angle in degrees.
        :param max_limit: The maximum angle in degrees.
        """

        super().__init__(id=id)
        """:field
        The minimum angle in degrees.
        """
        self.min_limit: float = min_limit
        """:field
        The maximum angle in degrees.
        """
        self.max_limit: float = max_limit
