# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_type_command import ObjectTypeCommand


class SetObjectDrag(ObjectTypeCommand):
    """
    Set the drag of an object's RigidBody. Both drag and angular_drag can be safely changed on-the-fly.
    """

    def __init__(self, id: int, drag: float = 0, angular_drag: float = 0.05):
        """
        :param id: The unique object ID.
        :param drag: Set the drag of the object's Rigidbody. A higher drag value will cause the object to slow down faster.
        :param angular_drag: Set the angular drag of the object's Rigidbody. A higher angular drag will cause the object's rotation to slow down faster.
        """

        super().__init__(id=id)
        """:field
        Set the drag of the object's Rigidbody. A higher drag value will cause the object to slow down faster.
        """
        self.drag: float = drag
        """:field
        Set the angular drag of the object's Rigidbody. A higher angular drag will cause the object's rotation to slow down faster.
        """
        self.angular_drag: float = angular_drag
