# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.vr_command import VrCommand


class SetVrLoadingScreen(VrCommand):
    """
    Show or hide the VR rig's loading screen.
    """

    def __init__(self, show: bool):
        """
        :param show: If true, show the loading screen. If false, hide it.
        """

        super().__init__()
        """:field
        If true, show the loading screen. If false, hide it.
        """
        self.show: bool = show
