# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.vr_command import VrCommand


class SetVrResolutionScale(VrCommand):
    """
    Controls the actual size of eye textures as a multiplier of the device's default resolution.
    """

    def __init__(self, resolution_scale_factor: float = 1.0):
        """
        :param resolution_scale_factor: Texture resolution scale factor. A value greater than 1.0 improves image quality but at a slight performance cost. Range: 0.5 to 1.75
        """

        super().__init__()
        """:field
        Texture resolution scale factor. A value greater than 1.0 improves image quality but at a slight performance cost. Range: 0.5 to 1.75
        """
        self.resolution_scale_factor: float = resolution_scale_factor
