# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.wheelchair_replicant_command import WheelchairReplicantCommand


class SetWheelchairSteerAngle(WheelchairReplicantCommand):
    """
    Set the steer angle of the wheelchair's front wheels.
    """

    def __init__(self, id: int, angle: float):
        """
        :param id: The unique object ID.
        :param angle: The angle in degrees.
        """

        super().__init__(id=id)
        """:field
        The angle in degrees.
        """
        self.angle: float = angle
