# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.post_process_command import PostProcessCommand


class SetVignette(PostProcessCommand):
    """
    Enable or disable the vignette, which darkens the image at the edges.
    """

    def __init__(self, enabled: bool = False):
        """
        :param enabled: If true, vignette is enabled.
        """

        super().__init__()
        """:field
        If true, vignette is enabled.
        """
        self.enabled: bool = enabled
