# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command


class SetFloorplanRoof(Command):
    """
    Show or hide the roof of a floorplan scene. This command only works if the current scene is a floorplan added via the add_scene command: "floorplan_1a", "floorplan_4b", etc.
    """

    def __init__(self, show: bool = True):
        """
        :param show: If true, show the roof.
        """

        super().__init__()
        """:field
        If true, show the roof.
        """
        self.show: bool = show
