# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_type_command import ObjectTypeCommand
from typing import Dict


class SetAngularVelocity(ObjectTypeCommand):
    """
    Set an object's angular velocity. This should ONLY be used on the same communicate() call in which the object is created. Otherwise, sending this command can cause physics glitches.
    """

    def __init__(self, id: int, velocity: Dict[str, float] = None):
        """
        :param id: The unique object ID.
        :param velocity: The angular velocity in radians per second.
        """

        super().__init__(id=id)
        if velocity is None:
            """:field
            The angular velocity in radians per second.
            """
            self.velocity: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.velocity = velocity
