# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.object_type_command import ObjectTypeCommand


class SetMass(ObjectTypeCommand):
    """
    Set the mass of an object.
    """

    def __init__(self, id: int, mass: float):
        """
        :param id: The unique object ID.
        :param mass: The new mass of the object.
        """

        super().__init__(id=id)
        """:field
        The new mass of the object.
        """
        self.mass: float = mass
