# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.show_hide_object import ShowHideObject


class ShowObject(ShowHideObject):
    """
    Show the object.
    """

    def __init__(self, id: int):
        """
        :param id: The unique object ID.
        """

        super().__init__(id=id)

