# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.adjust_textured_quad_command import AdjustTexturedQuadCommand


class ShowTexturedQuad(AdjustTexturedQuadCommand):
    """
    Show or hide a textured quad.
    """

    def __init__(self, id: int, show: bool = True):
        """
        :param id: The ID of the non-physics object.
        :param show: If True, show the quad. If False, hide it.
        """

        super().__init__(id=id)
        """:field
        If True, show the quad. If False, hide it.
        """
        self.show: bool = show
