# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command


class StepPhysics(Command):
    """
    Step through the physics without triggering new avatar output, or new commands.
    """

    def __init__(self, frames: int):
        """
        :param frames: Let the physics run for this many frames.
        """

        super().__init__()
        """:field
        Let the physics run for this many frames.
        """
        self.frames: int = frames
