# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command


class StopAllAudio(Command):
    """
    Stop all ongoing audio.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
