# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.video_capture_command import VideoCaptureCommand


class StopVideoCapture(VideoCaptureCommand):
    """
    Stop ongoing video capture.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
