# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.replicant_command import ReplicantCommand


class StopReplicantAnimation(ReplicantCommand):
    """
    Stop an ongoing Replicant animation.
    """

    def __init__(self, id: int):
        """
        :param id: The unique object ID.
        """

        super().__init__(id=id)

