# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.robot_command import RobotCommand
from typing import Dict


class TeleportRobot(RobotCommand):
    """
    Teleport the robot to a new position and rotation. This is a sudden movement that might disrupt the physics simulation. You should only use this command if you really need to (for example, if the robot falls over).
    """

    def __init__(self, position: Dict[str, float] = None, rotation: Dict[str, float] = None, id: int = 0):
        """
        :param position: The position of the robot.
        :param rotation: The rotation of the robot.
        :param id: The ID of the robot in the scene.
        """

        super().__init__(id=id)
        if position is None:
            """:field
            The position of the robot.
            """
            self.position: Dict[str, float] = {"x": 0, "y": 0, "z": 0}
        else:
            self.position = position
        if rotation is None:
            """:field
            The rotation of the robot.
            """
            self.rotation: Dict[str, float] = {"x": 0, "y": 0, "z": 0, "w": 1}
        else:
            self.rotation = rotation
