# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.empty_object_command import EmptyObjectCommand
from typing import Dict


class TeleportEmptyObject(EmptyObjectCommand):
    """
    Teleport an empty object to a new position.
    """

    def __init__(self, id: int, empty_object_id: int, position: Dict[str, float], rotation: Dict[str, float] = None, absolute: bool = True):
        """
        :param id: The unique object ID.
        :param empty_object_id: The ID of the empty object. This doesn't have to be the same as the object ID.
        :param position: The location to teleport to.
        :param rotation: The new local rotation of the empty object.
        :param absolute: If True, teleport the empty object in world coordinate space. If False, teleport the empty object in local coordinate space.
        """

        super().__init__(empty_object_id=empty_object_id, id=id)
        """:field
        The location to teleport to.
        """
        self.position: Dict[str, float] = position
        if rotation is None:
            """:field
            The new local rotation of the empty object.
            """
            self.rotation: Dict[str, float] = {"x": 0, "y": 0, "z": 0, "w": 1}
        else:
            self.rotation = rotation
        """:field
        If True, teleport the empty object in world coordinate space. If False, teleport the empty object in local coordinate space.
        """
        self.absolute: bool = absolute
