# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.avatar_command import AvatarCommand
from typing import Dict


class TeleportAvatarTo(AvatarCommand):
    """
    Teleport the avatar to a position.
    """

    def __init__(self, position: Dict[str, float], avatar_id: str = "a"):
        """
        :param position: The position to teleport to.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(avatar_id=avatar_id)
        """:field
        The position to teleport to.
        """
        self.position: Dict[str, float] = position
