# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command


class Terminate(Command):
    """
    Terminate the build.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
