# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.avatar_rigidbody_command import AvatarRigidbodyCommand


class TurnAvatarBy(AvatarRigidbodyCommand):
    """
    Apply a relative torque to the avatar.
    """

    def __init__(self, torque: float, avatar_id: str = "a"):
        """
        :param torque: The magnitude of the torque around the y axis.
        :param avatar_id: The ID of the avatar.
        """

        super().__init__(avatar_id=avatar_id)
        """:field
        The magnitude of the torque around the y axis.
        """
        self.torque: float = torque
