# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.obi_actor_command import ObiActorCommand
from tdw.obi_data.cloth.tether_particle_group import TetherParticleGroup


class UntetherObiClothSheet(ObiActorCommand):
    """
    Untether a cloth sheet at a specified position.
    """

    def __init__(self, id: int, tether_position: TetherParticleGroup):
        """
        :param id: The unique object ID.
        :param tether_position: The position that will be un-tethered.
        """

        super().__init__(id=id)
        """:field
        The position that will be un-tethered.
        """
        self.tether_position: TetherParticleGroup = tether_position
