# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.global_boolean_command import GlobalBooleanCommand


class UsePreSignedUrls(GlobalBooleanCommand):
    """
    Toggle whether to download asset bundles (models, scenes, etc.) directly from byte streams of S3 objects, or from temporary URLs that expire after ten minutes. Only send this command and set this to True if you're experiencing segfaults when downloading models from models_full.json Initial value = On Linux: True (use temporary URLs). On Windows and OS X: False (download S3 objects directly, without using temporary URLs).
    """

    def __init__(self, value: bool):
        """
        :param value: Boolean value.
        """

        super().__init__(value=value)

