# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.command import Command


class VideoCaptureCommand(Command, ABC):
    """
    These commands start and stop audio-visual capture using ffmpeg. These commands assume that you've already installed ffmpeg on your computer.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
