# AUTOGENERATED FROM C#. DO NOT MODIFY.

from abc import ABC
from tdw.commands.command import Command


class VrCommand(Command, ABC):
    """
    These commands utilize VR in TDW.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
