# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.commands.command import Command


class Wait(Command):
    """
    Pause the simulation for a duration.
    """

    def __init__(self, duration: float):
        """
        :param duration: Wait this many seconds.
        """

        super().__init__()
        """:field
        Wait this many seconds.
        """
        self.duration: float = duration
