# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.webgl.trials.tests.automated_test import AutomatedTest


class TrialServerTest(AutomatedTest):
    """
    This trial runs indefinitely and is used to test the Trial Server.
    """

    def __init__(self):
        """
        (no arguments)
        """

        super().__init__()
