# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class CameraMotionComplete(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCameraMotionComplete(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = CameraMotionComplete()
        x.Init(buf, n + offset)
        return x

    # CameraMotionComplete
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # CameraMotionComplete
    def AvatarId(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CameraMotionComplete
    def Motion(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

def CameraMotionCompleteStart(builder): builder.StartObject(2)
def CameraMotionCompleteAddAvatarId(builder, avatarId): builder.PrependUOffsetTRelativeSlot(0, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(avatarId), 0)
def CameraMotionCompleteAddMotion(builder, motion): builder.PrependUint8Slot(1, motion, 1)
def CameraMotionCompleteEnd(builder): return builder.EndObject()
