# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class Categories(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCategories(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = Categories()
        x.Init(buf, n + offset)
        return x

    # Categories
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # Categories
    def CategoryData(self, j):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += tdw.flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Category import Category
            obj = Category()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Categories
    def CategoryDataLength(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def CategoriesStart(builder): builder.StartObject(1)
def CategoriesAddCategoryData(builder, categoryData): builder.PrependUOffsetTRelativeSlot(0, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(categoryData), 0)
def CategoriesStartCategoryDataVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def CategoriesEnd(builder): return builder.EndObject()
