# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class CompositeObject(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCompositeObject(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = CompositeObject()
        x.Init(buf, n + offset)
        return x

    # CompositeObject
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # CompositeObject
    def Id(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CompositeObject
    def SubObjects(self, j):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += tdw.flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .SubObject import SubObject
            obj = SubObject()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CompositeObject
    def SubObjectsLength(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def CompositeObjectStart(builder): builder.StartObject(2)
def CompositeObjectAddId(builder, id): builder.PrependInt32Slot(0, id, 0)
def CompositeObjectAddSubObjects(builder, subObjects): builder.PrependUOffsetTRelativeSlot(1, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(subObjects), 0)
def CompositeObjectStartSubObjectsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def CompositeObjectEnd(builder): return builder.EndObject()
