# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class IsOnNavMesh(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsIsOnNavMesh(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = IsOnNavMesh()
        x.Init(buf, n + offset)
        return x

    # IsOnNavMesh
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # IsOnNavMesh
    def Position(self, j):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(tdw.flatbuffers.number_types.Float32Flags, a + tdw.flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # IsOnNavMesh
    def PositionAsNumpy(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(tdw.flatbuffers.number_types.Float32Flags, o)
        return 0

    # IsOnNavMesh
    def PositionLength(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IsOnNavMesh
    def IsOn(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(tdw.flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # IsOnNavMesh
    def Id(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def IsOnNavMeshStart(builder): builder.StartObject(3)
def IsOnNavMeshAddPosition(builder, position): builder.PrependUOffsetTRelativeSlot(0, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)
def IsOnNavMeshStartPositionVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def IsOnNavMeshAddIsOn(builder, isOn): builder.PrependBoolSlot(1, isOn, 0)
def IsOnNavMeshAddId(builder, id): builder.PrependInt32Slot(2, id, 0)
def IsOnNavMeshEnd(builder): return builder.EndObject()
