# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class Occlusion(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOcclusion(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = Occlusion()
        x.Init(buf, n + offset)
        return x

    # Occlusion
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # Occlusion
    def AvatarId(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Occlusion
    def Occluded(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Occlusion
    def Unoccluded(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def OcclusionStart(builder): builder.StartObject(3)
def OcclusionAddAvatarId(builder, avatarId): builder.PrependUOffsetTRelativeSlot(0, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(avatarId), 0)
def OcclusionAddOccluded(builder, occluded): builder.PrependUint8Slot(1, occluded, 0)
def OcclusionAddUnoccluded(builder, unoccluded): builder.PrependUint8Slot(2, unoccluded, 0)
def OcclusionEnd(builder): return builder.EndObject()
