# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class OculusTouchButtons(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOculusTouchButtons(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = OculusTouchButtons()
        x.Init(buf, n + offset)
        return x

    # OculusTouchButtons
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # OculusTouchButtons
    def Left(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OculusTouchButtons
    def Right(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def OculusTouchButtonsStart(builder): builder.StartObject(2)
def OculusTouchButtonsAddLeft(builder, left): builder.PrependInt32Slot(0, left, 0)
def OculusTouchButtonsAddRight(builder, right): builder.PrependInt32Slot(1, right, 0)
def OculusTouchButtonsEnd(builder): return builder.EndObject()
