# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class Random(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRandom(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = Random()
        x.Init(buf, n + offset)
        return x

    # Random
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # Random
    def Seed(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RandomStart(builder): builder.StartObject(1)
def RandomAddSeed(builder, seed): builder.PrependInt32Slot(0, seed, 0)
def RandomEnd(builder): return builder.EndObject()
