# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class RobotJointVelocities(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRobotJointVelocities(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = RobotJointVelocities()
        x.Init(buf, n + offset)
        return x

    # RobotJointVelocities
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # RobotJointVelocities
    def Id(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RobotJointVelocities
    def Joints(self, j):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += tdw.flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .JointVelocities import JointVelocities
            obj = JointVelocities()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RobotJointVelocities
    def JointsLength(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def RobotJointVelocitiesStart(builder): builder.StartObject(2)
def RobotJointVelocitiesAddId(builder, id): builder.PrependInt32Slot(0, id, 0)
def RobotJointVelocitiesAddJoints(builder, joints): builder.PrependUOffsetTRelativeSlot(1, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(joints), 0)
def RobotJointVelocitiesStartJointsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def RobotJointVelocitiesEnd(builder): return builder.EndObject()
