# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class Room(object):
    __slots__ = ['_tab']

    # Room
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # Room
    def Id(self): return self._tab.Get(tdw.flatbuffers.number_types.Int32Flags, self._tab.Pos + tdw.flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Room
    def Center(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 4)
        return obj

    # Room
    def Extents(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 16)
        return obj


def CreateRoom(builder, id, center_x, center_y, center_z, extents_x, extents_y, extents_z):
    builder.Prep(4, 28)
    builder.Prep(4, 12)
    builder.PrependFloat32(extents_z)
    builder.PrependFloat32(extents_y)
    builder.PrependFloat32(extents_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(center_z)
    builder.PrependFloat32(center_y)
    builder.PrependFloat32(center_x)
    builder.PrependInt32(id)
    return builder.Offset()
