# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class SceneRegions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSceneRegions(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = SceneRegions()
        x.Init(buf, n + offset)
        return x

    # SceneRegions
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # SceneRegions
    def Regions(self, j):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += tdw.flatbuffers.number_types.UOffsetTFlags.py_type(j) * 28
            from .SceneRegion import SceneRegion
            obj = SceneRegion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SceneRegions
    def RegionsLength(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SceneRegionsStart(builder): builder.StartObject(1)
def SceneRegionsAddRegions(builder, regions): builder.PrependUOffsetTRelativeSlot(0, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(regions), 0)
def SceneRegionsStartRegionsVector(builder, numElems): return builder.StartVector(28, numElems, 4)
def SceneRegionsEnd(builder): return builder.EndObject()
