# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class StaticPrismaticJoint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStaticPrismaticJoint(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = StaticPrismaticJoint()
        x.Init(buf, n + offset)
        return x

    # StaticPrismaticJoint
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # StaticPrismaticJoint
    def Id(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StaticPrismaticJoint
    def Axis(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .Vector3 import Vector3
            obj = Vector3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StaticPrismaticJoint
    def Limit(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def StaticPrismaticJointStart(builder): builder.StartObject(3)
def StaticPrismaticJointAddId(builder, id): builder.PrependInt32Slot(0, id, 0)
def StaticPrismaticJointAddAxis(builder, axis): builder.PrependStructSlot(1, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(axis), 0)
def StaticPrismaticJointAddLimit(builder, limit): builder.PrependFloat32Slot(2, limit, 0.0)
def StaticPrismaticJointEnd(builder): return builder.EndObject()
