# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class StaticMotor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsStaticMotor(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = StaticMotor()
        x.Init(buf, n + offset)
        return x

    # StaticMotor
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # StaticMotor
    def Id(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StaticMotor
    def Force(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def StaticMotorStart(builder): builder.StartObject(2)
def StaticMotorAddId(builder, id): builder.PrependInt32Slot(0, id, 0)
def StaticMotorAddForce(builder, force): builder.PrependFloat32Slot(1, force, 0.0)
def StaticMotorEnd(builder): return builder.EndObject()
