# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class Volumes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVolumes(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = Volumes()
        x.Init(buf, n + offset)
        return x

    # Volumes
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # Volumes
    def Objects(self, j):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += tdw.flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from .VolumeData import VolumeData
            obj = VolumeData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Volumes
    def ObjectsLength(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def VolumesStart(builder): builder.StartObject(1)
def VolumesAddObjects(builder, objects): builder.PrependUOffsetTRelativeSlot(0, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(objects), 0)
def VolumesStartObjectsVector(builder, numElems): return builder.StartVector(8, numElems, 4)
def VolumesEnd(builder): return builder.EndObject()
