# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.webgl.trials.trial import Trial


class HelloWorld(Trial):
    """
    A hello world test trial.
    """

    def __init__(self, framerate: int = 60, render_quality: int = 5):
        """
        :param framerate: The target framerate.
        :param render_quality: The render quality (0 to 5, where 5 is best).
        """

        super().__init__(framerate=framerate, render_quality=render_quality)

