# AUTOGENERATED FROM C#. DO NOT MODIFY.

from tdw.webgl.trials.trial import Trial


class TestScene(Trial):
    """
    This trial adds a scene, an object, and a camera. It runs until the object stops moving. This trial is meant to be used to debug basic WebGL functionality.
    """

    def __init__(self, framerate: int = 60, render_quality: int = 5):
        """
        :param framerate: The target framerate.
        :param render_quality: The render quality (0 to 5, where 5 is best).
        """

        super().__init__(framerate=framerate, render_quality=render_quality)

